apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: spring-boot-backend-main
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
