apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
        - image: ghcr.io/nus-iss-devsecops-2024-project-app/backend-spring-boot-app:2be4a08183bca6f81e65bccc3822b9710053654b
          name: backend
          resources: {}
